import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./apple-theme.css";
import ThemeProviderWrapper from '@/components/providers/ThemeProviderWrapper';
import AuthProviderWrapper from '@/components/providers/AuthProviderWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "House Pros Hub",
  description: "Generated by create next app",
  icons: {
    icon: '/fav.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProviderWrapper>
          <AuthProviderWrapper>
            {children}
          </AuthProviderWrapper>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
