import { ProCardData } from '@/components/proscard/ProCard';

export const sampleProCards: ProCardData[] = [
  {
    id: '2',
    businessName: 'XYZ Roofing Co',
    contractorType: 'Roofing Contractor',
    tradeIcon: 'Home',
    category: 'Roofing',
    links: [
      { type: 'phone', value: '555-5678' },
      { type: 'website', url: 'https://xyz-roofing.com' },
      { type: 'email', value: 'contact@xyz-roofing.com' },
      { type: 'instagram', url: 'https://instagram.com/xyz_roofing' },
      { type: 'facebook', url: 'https://facebook.com/xyz_roofing' },
    ],
    reactions: {
      love: 38,
      feedback: 12,
      link: 5,
      save: 19,
    },
  },
  {
    id: '3',
    businessName: 'Elite Tile Works',
    contractorType: 'Tile Contractor',
    tradeIcon: 'Grid3x3',
    category: 'Tile',
    links: [
      { type: 'phone', value: '555-9012' },
      { type: 'website', url: 'https://elite-tile.com' },
      { type: 'instagram', url: 'https://instagram.com/elite_tile' },
    ],
    reactions: {
      love: 29,
      feedback: 8,
      link: 3,
      save: 14,
    },
  },
  {
    id: '4',
    businessName: 'Premier Plumbing',
    contractorType: 'Plumbing Contractor',
    tradeIcon: 'Droplet',
    category: 'Plumbing',
    links: [
      { type: 'phone', value: '555-3456' },
      { type: 'website', url: 'https://premier-plumbing.com' },
      { type: 'email', value: 'info@premier-plumbing.com' },
      { type: 'calendar', url: 'https://calendly.com/premier' },
    ],
    reactions: {
      love: 51,
      feedback: 22,
      link: 10,
      save: 31,
    },
  },
  {
    id: '5',
    businessName: 'Spark Electric',
    contractorType: 'Electrical Contractor',
    tradeIcon: 'Zap',
    category: 'Electrical',
    links: [
      { type: 'phone', value: '555-7890' },
      { type: 'website', url: 'https://spark-electric.com' },
      { type: 'email', value: 'info@spark-electric.com' },
      { type: 'instagram', url: 'https://instagram.com/spark_electric' },
      { type: 'calendar', url: 'https://calendly.com/spark' },
    ],
    reactions: {
      love: 45,
      feedback: 18,
      link: 7,
      save: 28,
    },
  },
  {
    id: '6',
    businessName: 'Cool Breeze HVAC',
    contractorType: 'HVAC Contractor',
    tradeIcon: 'Wind',
    category: 'HVAC',
    links: [
      { type: 'phone', value: '555-2468' },
      { type: 'website', url: 'https://coolbreeze-hvac.com' },
      { type: 'email', value: 'service@coolbreeze-hvac.com' },
      { type: 'facebook', url: 'https://facebook.com/coolbreeze_hvac' },
    ],
    reactions: {
      love: 62,
      feedback: 25,
      link: 12,
      save: 35,
    },
  },
  {
    id: '7',
    businessName: 'Pro Paint Co',
    contractorType: 'Painting Contractor',
    tradeIcon: 'Paintbrush',
    category: 'Painting',
    links: [
      { type: 'phone', value: '555-3691' },
      { type: 'website', url: 'https://propaint.com' },
      { type: 'instagram', url: 'https://instagram.com/propaint' },
      { type: 'email', value: 'info@propaint.com' },
    ],
    reactions: {
      love: 34,
      feedback: 11,
      link: 4,
      save: 19,
    },
  },
  {
    id: '8',
    businessName: 'Solid Foundation Builders',
    contractorType: 'Foundation Contractor',
    tradeIcon: 'Layers',
    category: 'Flooring',
    links: [
      { type: 'phone', value: '555-1470' },
      { type: 'website', url: 'https://solidfoundation.com' },
      { type: 'email', value: 'contact@solidfoundation.com' },
      { type: 'calendar', url: 'https://calendly.com/solidfoundation' },
    ],
    reactions: {
      love: 48,
      feedback: 20,
      link: 9,
      save: 32,
    },
  },
  {
    id: '9',
    businessName: 'Window Masters',
    contractorType: 'Window & Door Contractor',
    tradeIcon: 'DoorOpen',
    category: 'Windows',
    links: [
      { type: 'phone', value: '555-8520' },
      { type: 'website', url: 'https://windowmasters.com' },
      { type: 'instagram', url: 'https://instagram.com/windowmasters' },
      { type: 'facebook', url: 'https://facebook.com/windowmasters' },
    ],
    reactions: {
      love: 41,
      feedback: 16,
      link: 6,
      save: 26,
    },
  },
  {
    id: '10',
    businessName: 'Green Thumb Landscaping',
    contractorType: 'Landscaping Contractor',
    tradeIcon: 'TreePine',
    category: 'Landscape',
    links: [
      { type: 'phone', value: '555-1111' },
      { type: 'website', url: 'https://greenthumb-landscaping.com' },
      { type: 'instagram', url: 'https://instagram.com/greenthumb' },
      { type: 'email', value: 'info@greenthumb-landscaping.com' },
    ],
    reactions: {
      love: 55,
      feedback: 20,
      link: 9,
      save: 30,
    },
  },
  {
    id: '11',
    businessName: 'Perfect Pavers',
    contractorType: 'Paving Contractor',
    tradeIcon: 'Square',
    category: 'Pavers',
    links: [
      { type: 'phone', value: '555-2222' },
      { type: 'website', url: 'https://perfectpavers.com' },
      { type: 'facebook', url: 'https://facebook.com/perfectpavers' },
      { type: 'email', value: 'contact@perfectpavers.com' },
    ],
    reactions: {
      love: 43,
      feedback: 17,
      link: 8,
      save: 27,
    },
  },
  {
    id: '12',
    businessName: 'Elite Doors & More',
    contractorType: 'Door Contractor',
    tradeIcon: 'DoorOpen',
    category: 'Doors',
    links: [
      { type: 'phone', value: '555-3333' },
      { type: 'website', url: 'https://elitedoors.com' },
      { type: 'instagram', url: 'https://instagram.com/elitedoors' },
      { type: 'calendar', url: 'https://calendly.com/elitedoors' },
    ],
    reactions: {
      love: 39,
      feedback: 14,
      link: 6,
      save: 24,
    },
  },
  {
    id: '13',
    businessName: 'Secure Fence Solutions',
    contractorType: 'Fencing Contractor',
    tradeIcon: 'Fence',
    category: 'Fencing',
    links: [
      { type: 'phone', value: '555-4444' },
      { type: 'website', url: 'https://securefence.com' },
      { type: 'email', value: 'info@securefence.com' },
      { type: 'facebook', url: 'https://facebook.com/securefence' },
    ],
    reactions: {
      love: 47,
      feedback: 19,
      link: 7,
      save: 29,
    },
  },
  {
    id: '14',
    businessName: 'Premium Deck Builders',
    contractorType: 'Decking Contractor',
    tradeIcon: 'Layout',
    category: 'Decking',
    links: [
      { type: 'phone', value: '555-5555' },
      { type: 'website', url: 'https://premiumdeck.com' },
      { type: 'instagram', url: 'https://instagram.com/premiumdeck' },
      { type: 'email', value: 'contact@premiumdeck.com' },
    ],
    reactions: {
      love: 52,
      feedback: 21,
      link: 10,
      save: 33,
    },
  },
];

